# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d769356df753b2feaa10dcbdb2836d3b6388c0794551d65b9b1c4800ed56d73f2a95f80705c2bd915bceb5710395874ce31c48c0dda51347b694497c4edf5be7

test:
  secret_key_base: cd60e4f145daf7ac7e9e2e61ad85ca73a6d766b3861bd76dc5feb10fb3f8b87e12e3800daf5d6e0e85b517fc87950d8b78e82679a8475efc23a364ec662cac7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
